POST  http://localhost:3001/register
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJpYXQiOjE2NTI2ODk5NDR9.zij0-NOrpBDzJxKr_wx26CZvqHrg_h9vrgqH5YvFC3s'
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "123"

}
###
GET http://localhost:3001/test